name: cicd pipeline

on:
  push:
  workflow_dispatch:
    #branches: [ "main" ]

jobs:
  docker_build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4
      
      - name: Build all services
        run: |
         for dir in src/*/ ; do
         service=$(basename "$dir")
         echo "🚀 Building $service..."
          if [ "$service" = "cartservice" ]; then     # Special case for cartservice
           docker build -t "$service:latest" "$dir/src"
           else
           docker build -t "$service:latest" "$dir"
         fi
         done

      - name: Smoke test app (using docker-compose)
        run: |
         docker compose up -d
         sleep 30
         curl -f http://localhost:8080/ || (echo "❌ App failed" && exit 1)
         docker compose down
       
