name: cicd pipeline

on:
  workflow_dispatch:
  #push:
   # branches: ["main"]

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install docker
        run: |
          sudo apt update
          sudo apt install docker.io
          sudo systemctl enable docker
          sudo systemctl start docker
          sudo groupadd docker                 # Create group if not exists
          sudo usermod -aG docker $USER        # Add your user to the docker group
          newgrp docker                       # Refresh group membership, or logout/login

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build all services
        run: | 
          for dir in src/*/ ; do 
            service=$(basename "$dir") 
            echo "🚀 Building $service..." 
            if [ "$service" = "cartservice" ]; 
            then 
              context="$dir/src" 
            else 
              context="$dir" 
            fi 
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest "$context" 
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest
          done

    - name: Deploy services one by one to k8s
      run: 
#      - name: Install kubectl
#        run: |
#            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
#           chmod +x kubectl
#            sudo mv kubectl /usr/local/bin/
#            kubectl version --client

#      - name: Install kind and create cluster
#        run: |
#         curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.30.0/kind-$(uname)-amd64
#          chmod +x ./kind
#          sudo mv ./kind /usr/local/bin/kind
#          kind create cluster
#          kubectl get nodes   # If this returns a list of nodes, your context and kubeconfig are working correctly.

# This is not a pipeline step, but noting it here as above has been sequence since beginning: 
# 1) curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
#    chmod 700 get_helm.sh
#    ./get_helm.sh

# 2) helm create microservice-helmchart   .. a helm chart of name microservice-helmchart will be created, names[ace is default
 
               
