name: cicd pipeline

on:
  workflow_dispatch:
  #push:
   # branches: ["main"]

jobs:
  docker_build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build all services
        run: | 
          for dir in src/*/ ; do 
            service=$(basename "$dir") 
            echo "🚀 Building $service..." 
            if [ "$service" = "cartservice" ]; 
            then 
              context="$dir/src" 
            else 
              context="$dir" 
            fi 
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest "$context" 
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest
          done

#      - name: Install kubelet
#        run: |
#            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
#           chmod +x kubectl
#            sudo mv kubectl /usr/local/bin/
#            kubectl version --client

#      - name: Install kind and create cluster
#        run: |
#         curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.30.0/kind-$(uname)-amd64
#          chmod +x ./kind
#          sudo mv ./kind /usr/local/bin/kind
#          kind create cluster
 #          kubectl get nodes   # If this returns a list of nodes, your context and kubeconfig are working correctly.

 
               
