name: cicd pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  docker_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
       for dir in src/*/ ; do
        service=$(basename "$dir")
        echo "🚀 Building $service..."
        docker build -t $service:latest $dir
       done

    - name: Smoke test app (using docker-compose)
      run: |
       docker compose up -d
       sleep 30
       curl -f http://localhost:8080/ || (echo "❌ App failed" && exit 1)
       docker compose down
       
